name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        c_compiler: [gcc, clang, cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang
          - os: ubuntu-latest
            c_compiler: cl

    steps:
    - uses: actions/checkout@v4

    - name: Linux - Installing dependencies
      if: runner.os == 'Linux'
      run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake xorg-dev libglu1-mesa-dev libglfw3-dev xvfb libglew-dev wget
          wget https://github.com/KhronosGroup/KTX-Software/releases/download/v4.4.2/KTX-Software-4.4.2-Linux-x86_64.deb
          sudo apt-get install ./KTX-Software-4.4.2-Linux-x86_64.deb

    - name: Windows - Setting up dependencies and OpenGL
      if: runner.os == 'Windows'
      shell: bash
      run: |
        $VCPKG_INSTALLATION_ROOT/vcpkg install glfw3:x64-windows
        $VCPKG_INSTALLATION_ROOT/vcpkg install ktx:x64-windows
        $VCPKG_INSTALLATION_ROOT/vcpkg install glew:x64-windows

    - name: Set reusable strings
      # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Linux - Configure Project
      if: runner.os == 'Linux'
      run: |
          cmake -S . -B ${{ steps.strings.outputs.build-output-dir }} \
            -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
            -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
            -DCMAKE_BUILD_TYPE=\${{ matrix.build_type }}

    - name: Windows - Configure Project
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
          cmake -S . -B ${{ github.workspace }}/build `
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} `
            -DCMAKE_CXX_COMPILER=cl `
            -DCMAKE_C_COMPILER=cl `
            -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake" `
            -DVCPKG_TARGET_TRIPLET=x64-windows `
            -DVCPKG_MANIFEST_MODE=OFF

    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }}

    - name: Linux - Test
      if: runner.os == 'Linux'
      working-directory: ${{ github.workspace }}
      run: xvfb-run -a --server-args="-screen 0 1280x1024x24" ctest --test-dir build/ --build-config "${{ matrix.build_type }}" --output-on-failure

    - name: Windows - Test
      if: runner.os == 'Windows'
      working-directory: ${{ github.workspace }}
      run: ctest --test-dir build/ --build-config "${{ matrix.build_type }}" --output-on-failure
